language: node_js
node_js:
    - "0.10"

addons:
  sauce_connect:
    username: "rfwebb"
    secure: "KWyj/JW4wUEL3NXOVX0lBbPQ1EyJXGAHWhvj3VpdOZ/V81G7ZWTKD+etyPbNyxp1liapZ04sLU9p3cFpdPoP8R7U2jShalwVgBnphqbddK37xri5WhOtTcxnHWVEwY3psqhzUIRgs/5p+G5sTrsCOCfsHFKzz+6ZHLTHikHQxHI="

install:
    - npm install
    - sudo apt-get update -qq
    - sudo apt-get install -y graphicsmagick
    - git clone https://github.com/ZoetropeImaging/zoetrope-jquery

script:
    - cd zoetrope-jquery
    - npm install
    - gulp
    - cd ..
    - http-server -p 8888 zoetrope-jquery/dist  # start a Web server
    - sleep 3 # give Web server some time to bind to sockets, etc
    - cd tests
    - protractor testSuite.conf.js
